---
### Required zabbix-python package
- name: Create a new host or update an existing host's info (required zabbix-python package)
  local_action:
    module: zabbix_host
    server_url: https://127.0.0.1/zabbix
    login_user: ZabbixAPIuser
    login_password: ChangeMe123
    host_name: "{{ zabbix_hostname }}"
    host_groups:
      - "{{ zabbix_host_group }}"
    link_templates:
      - "Template OS Linux"
    status: enabled
    state: present
    force: no
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: ""
        port: 10050
