---
- name: Copying zabbix-agent config
  copy:
    src: etcd/etcd.conf
    dest: /etc/zabbix/zabbix_agentd.d/etcd.conf
    mode: 0755
    owner: zabbix
    group: zabbix

- name: installing curl package
  package:
    name: smartmontools
    state: present