---
- name: Install Agent
  apt: name=zabbix-agent state=latest update_cache=yes
  become: yes
  when: zabbix_agent_check_deb.rc == 1

- name: Put config file
  template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    force: yes
  become: yes