---
- name: Create directory if not exists
  become: yes
  file:
    path: /etc/zabbix/scripts/microservices/
    state: directory
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Copying get.data script
  become: yes
  copy:
    src: microservice/microservice.get.data.py
    dest: /etc/zabbix/scripts/microservices/microservice.get.data.py
    mode: 0755
    owner: zabbix
    group: zabbix 

- name: Copying parse script
  become: yes
  copy:
    src: microservice/microservice.parse.py
    dest: /etc/zabbix/scripts/microservices/microservice.parse.py
    mode: 0755
    owner: zabbix
    group: zabbix 

- name: Copying zabbix-agent config
  become: yes
  copy:
    src: microservice/microservice.status.conf
    dest: /etc/zabbix/zabbix_agentd.d/microservice.status.conf
    mode: 0755
    owner: zabbix
    group: zabbix
