---
- name: Create directory if not exists
  file:
    path: /etc/zabbix/scripts/
    state: directory
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Copying shell script
  copy:
    src: nginx/nginx-rtmp.sh
    dest: /etc/zabbix/scripts/nginx-rtmp.sh
    mode: 0755
    owner: zabbix
    group: zabbix 

- name: Creating tmp file for status collecting
  file: 
    path: /tmp/rtmp_nginx.tmp
    state: touch 
    mode: 0777

- name: Copying zabbix-agent config
  copy:
    src: nginx/nginx-rtmp.conf
    dest: /etc/zabbix/zabbix_agentd.d/nginx-rtmp.conf
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Restart Nginx Sysvinit
  service: name=nginx state=reloaded enabled=yes
  become: yes
  when: ansible_distribution_release == "trusty" or ansible_distribution_release == "wheezy"

- name: Restart Nginx Systemd
  systemd: name=nginx state=reloaded daemon_reload=yes enabled=yes
  become: yes
  when: ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie"
