---
- name: Create directory if not exists
  file:
    path: /etc/zabbix/scripts/
    state: directory
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Copying shell script
  copy:
    src: nginx/nginx_status.sh
    dest: /etc/zabbix/scripts/nginx_status.sh
    mode: 0755
    owner: zabbix
    group: zabbix 

- name: Create tmp file for status collect
  file: path=/tmp/status_nginx.tmp state=touch mode=0777

- name: Copying nginx-config
  copy:
    src: nginx/nginx-status.conf
    dest: /etc/nginx/conf.d/nginx-status.conf
    mode: 0755

- name: Copying zabbix-agent config
  copy:
    src: nginx/nginx.conf
    dest: /etc/zabbix/zabbix_agentd.d/nginx.conf
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Restart Nginx Sysvinit
  service: name=nginx state=reloaded enabled=yes
  become: yes
  when: ansible_distribution_release == "trusty" or ansible_distribution_release == "wheezy"

- name: Restart Nginx Systemd
  systemd: name=nginx state=reloaded daemon_reload=yes enabled=yes
  become: yes
  when: ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie"
