---
- name: Create directory if not exist
  become: yes
  file:
    path: /etc/zabbix/scripts/
    state: directory
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Copying php-script
  become: yes
  copy:
    src: php-fpm/status.php
    dest: /etc/zabbix/scripts/status.php
    owner: zabbix
    group: zabbix
    mode: 0755

- name: Copying shell script
  become: yes
  copy:
    src: php-fpm/php-fpm.sh
    dest: /etc/zabbix/scripts/php-fpm_status.sh
    mode: 0755
    owner: zabbix
    group: zabbix 

- name: Copying nginx-config
  become: yes
  copy:
    src: php-fpm/status.conf
    dest: /etc/nginx/conf.d/status.conf
    mode: 0755

- name: Copying zabbix-agent config
  become: yes  
  copy:
    src: php-fpm/php-fpm.conf
    dest: /etc/zabbix/zabbix_agentd.d/php-fpm.conf
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Creating status tmpfile
  become: yes
  file:
    path: /tmp/php_fpm_status.tmp
    state: touch
    owner: zabbix
    group: zabbix
    mode: 0755

- name: Reload Nginx Sysvinit
  service: name=nginx state=reloaded enabled=yes
  become: yes
  when: ansible_distribution_release == "trusty" or ansible_distribution_release == "wheezy"

- name: Reload Nginx Systemd
  systemd: name=nginx state=reloaded daemon_reload=yes enabled=yes
  become: yes
  when: ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie"


- name: Stop PHP-FPM Sysvinit
  service: name=php7.0-fpm state=stopped enabled=yes
  become: yes
  when: ansible_distribution_release == "trusty" or ansible_distribution_release == "wheezy"

- name: Stop PHP-FPM Systemd
  systemd: name=php7.0-fpm state=stopped daemon_reload=yes enabled=yes
  become: yes
  when: ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie"

- name: Start PHP-FPM Sysvinit
  service: name=php7.0-fpm state=started enabled=yes
  become: yes
  when: ansible_distribution_release == "trusty" or ansible_distribution_release == "wheezy"

- name: Start PHP-FPM Systemd
  systemd: name=php7.0-fpm state=started daemon_reload=yes enabled=yes
  become: yes
  when: ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie"
