---
- name: Create directory if not exist
  file:
    path: /etc/zabbix/scripts/
    state: directory
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Copying zabbix-config
  copy: 
    src: postgresql/postgresql.conf
    dest: /etc/zabbix/zabbix_agentd.d/postgresql.conf
    mode: 0755
    owner: zabbix
    group: zabbix
