---
- name: Creating zabbix-scripts directory if not exist
  become: yes
  file:
    path: /etc/zabbix/scripts/
    state: directory
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Installing smartmontools package
  become: yes
  package:
    name: smartmontools
    state: present

- name: Copying smartctl perl-script
  become: yes
  copy:
    src: smartmontools/smartctl-disks-discovery.pl
    dest: /etc/zabbix/scripts/smartctl-disks-discovery.pl
    mode: 0755
    owner: zabbix
    group: zabbix 

- name: Set mode to perl-script
  become: yes
  file:
    path: /etc/zabbix/scripts/smartctl-disks-discovery.pl
    mode: a+x

- name: Copying smartctl shell-script
  become: yes
  copy:
    src: smartmontools/smart.thresh.check.sh
    dest: /etc/zabbix/scripts/smart.thresh.check.sh
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Set mode to perl-script
  become: yes
  file: 
    path: /etc/zabbix/scripts/smart.thresh.check.sh
    mode: a+x

- name: Copying zbx-smartctl-config
  become: yes
  copy: 
    src: smartmontools/zabbix_smartctl.conf
    dest: /etc/zabbix/zabbix_agentd.d/zabbix_smartctl.conf
    mode: 0755
    owner: zabbix
    group: zabbix

- name: Allow zabbix-user execute perl-script
  become: yes
  blockinfile:
    path: /etc/sudoers 
    block: |
      zabbix ALL= (ALL) NOPASSWD: /usr/sbin/smartctl,/etc/zabbix/scripts/smartctl-disks-discovery.pl,/etc/zabbix/scripts/smart.thresh.check.sh

- name: Restarting ssh server
  service: name=ssh state=restarted enabled=yes
  become: yes