---
- name: Istalling git package
  become: yes
  package:
    name: git
    state: latest

- name: Cloning fail2ban
  become: yes
  git:
    repo: https://github.com/sebres/fail2ban.git
    dest: /tmp/fail2ban
    clone: yes
    update: yes

- name: Installing fail2ban
  become: yes
  command: /usr/bin/python setup.py install
  args:
    chdir: /tmp/fail2ban

- name: Starting fail2ban
  command: /usr/local/bin/fail2ban-client -b start
  become: yes

- name: Deleting temporary file
  become: yes
  file:
    state: absent
    path: /tmp/fail2ban/
