---
- name: Update cache
  apt: update_cache=yes
  become: yes

- name: Install Utils
  apt: name={{ item }}
  with_items:
      - sudo
      - locales
      - unattended-upgrades
      - aptitude
      - unzip
  become: yes

- name: Upgrade packages
  apt: upgrade=full
  become: yes